nodeLinker: node-modules
enableGlobalCache: true

npmRegistryServer: "https://registry.npmjs.org"
npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmAlwaysAuth: true

# чтобы @sayyyat точно публиковался в npmjs
npmScopes:
  sayyyat:
    npmRegistryServer: "https://registry.npmjs.org"
