nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  sayyyat:
    npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NODE_AUTH_TOKEN}"

# If you see the error below when running yarn commands, it means that the NODE_AUTH_TOKEN
# environment variable is not set in your system.
# Usage Error: Environment variable not found (NODE_AUTH_TOKEN) in ...
# 
# for local releases, use this command to set a dummy token
#
# powershell
# $env:NODE_AUTH_TOKEN="DUMMY_FOR_LOCAL_RELEASE" 
#
# bash
# export NODE_AUTH_TOKEN="DUMMY_FOR_LOCAL_RELEASE"
#
# cmd
# set NODE_AUTH_TOKEN=DUMMY_FOR_LOCAL_RELEASE